### DISCUSSION TITLE
PostgreSQL Data Node configuration

### DISCUSSION THREAD

**Discussion by s-wel** [Avaiga/taipy#116] [Q&A] [answered]
Hi, I am experimenting with Taipy 2.1 and an SQL data node that I want to connect to a PostgreSQL database (version 11). The database is a TrackerStore for a "Rasa" chatbot (https://rasa.com/docs/rasa/tracker-stores/#sqltrackerstore). Since the documentation (https://docs.taipy.io/en/latest/manuals/core/config/data-node-config/#sql) does not cover the configuration for postgresql, I face some problems getting it to work - but I don't know if it is because of a misconfiguration or another problem.

This is my TOML file with the data node definition:
``` TOML
[DATA_NODE.TrackerStore]
storage_type = "sql"
db_username = "admin"
db_password = "xxx"
db_extra_args={}
db_name = "mydb"
db_engine = "postgresql"
read_query = "my query"
db_port = "5432"
db_host = "my host"
table_name = "my table name"
write_query_builder = "mymodule.write_query_builder:function"
scope = "SCENARIO:SCOPE"
```

This is the python script I use to execute the scenario:
``` Python
    Config.configure_job_executions(mode="development")

    Config.load('myfile.toml')

    # base is the id of the scenario configured
    scenario_cfg = Config.scenarios['base']

    Config.check()

    # Run of the Core
    tp.Core().run()

    # Creation of the scenario and execution
    scenario = tp.create_scenario(scenario_cfg)
    tp.submit(scenario)

    print(scenario.output.read())
```

When executing this, the console raises an error:
`AttributeError: output is not an attribute of scenario SCENARIO_base_f5008b88-47e9-448a-ab58-2368018d59ec`
and a related error:
`psycopg2.ProgrammingError: invalid dsn: invalid connection option "driver"`

What does the error mean? Is it a configuration problem, e.g. missing driver specification? How can I fix it?
