### DISCUSSION TITLE
Taipy vs Gradio - tools for working with natural language data

### DISCUSSION THREAD

**Discussion by s-wel** [Avaiga/taipy#248] [Q&A]
Hello, I am working on an open source tool that I can use to configure and manage chatbots. I mainly work with natural language data and event data. I managed to build small taipy applications to monitor chatbots already (analyzing event logs). A next step for us is to build interfaces for translation, annotation, and a chat box. In parallel, we found a Python framework called Gradio (https://github.com/gradio-app/gradio) that seems to do similar things compared to Taipy but with a stronger focus on natural language data. Probably there are other frameworks like it too.

What are your opinions and experiences about using taipy for natural language data?
Will there be any specific taipy GUI elements to simplify working with language data?

**Comment by FlorianJacta** [comment]
Taipy offers a wide range of visual elements: input, text, table, and images, ... All of them are fully customizable and very interactive. If needed, other visual elements can be added by anyone through the Taipy extension API. Taipy is designed (but not restricted) to build larger applications than Gradio and offers much more flexibility in creating applications. It also encapsulates a way to create the backend of your application to manage your data and functions (called [Taipy Core](https://docs.taipy.io/en/latest/manuals/core/)).

Here is an Taipy demo using GPT and Dall-e to generate tweets and images:

https://tweet-generation.taipy.cloud/

https://github.com/Avaiga/demo-tweet-generation/tree/develop/src

![image](https://github.com/Avaiga/taipy/assets/98709993/5ae189d5-1fa0-428a-9ede-dfab2fe46ab1)


This kind of complete application is outside the scope of Gradio. Gradio is more focused on connecting itself to one particular model and creating a 'widget' around it.

Of course, we are always happy to know what you need and see if we can help you. We can even include your requests in Taipy directly.

Here is another quick code to create a ChatGPT chatbot; I used a Taipy table to make the interface:

![image](https://github.com/Avaiga/taipy/assets/98709993/71fdc09e-b9a2-44b4-94df-01e405119fed)


*main.py* (almost all the code is just Python)

```python
from taipy.gui import Gui
import openai

# Define OpenAI API key 
openai.api_key = "OPENAI-KEY"

# Set up the model and prompt
model_engine = "text-davinci-003"

text_for_gpt = "The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.\n\nHuman: Hello, who are you?\nAI: I am an AI created by OpenAI. How can I help you today? "
conversation = {"Discussion":[]}
current_user_message = ""

def request(prompt):
    # Generate a response
    completion = openai.Completion.create(
        engine=model_engine,
        prompt=prompt,
        max_tokens=1024,
        n=1,
        stop=None,
        temperature=0.5,
    )

    response = completion.choices[0].text
    return response


page = """
<br/>
<|{conversation}|table|style={lambda state, idx, row: "user_message" if idx % 2 == 0 else "gpt_message"}|show_all|width=100%|>
<br/>

<|{current_user_message}|input|label=Text to send|on_action=send_message|class_name=fullwidth|> 

<| 📨 Send|button|on_action=send_message|>
"""


def send_message(state):
    answer = request_gpt(state)
    conv = state.conversation._dict.copy()
    conv['Discussion'] +=  [state.current_user_message, answer]
    state.current_user_message = ""
    state.conversation = conv


def request_gpt(state):
    state.text_for_gpt += f"Human: \n {state.current_user_message}\n\n AI:"
    answer = request(state.text_for_gpt).replace('\n', '')
    state.text_for_gpt += answer
    return answer


Gui(page).run()
```

*main.css* (this is optional, it is just here to style the table as we want)
```css
.gpt_message td  {
    margin-left: 20px;
    margin-bottom: 10px;
    position: relative;
    display: inline-block;
    padding: 10px;
    background-color: #9ea4ae;
    border: 1px solid #9ea4ae;
    border-radius: 10px;
    max-width: 30%;
}

.user_message td  {
    margin-left: 20px;
    margin-bottom: 10px;
    position: relative;
    display: inline-block;
    padding: 10px;
    background-color: #6f91cb;
    border: 1px solid #6f91cb;
    border-radius: 10px;
    max-width: 30%;
    float: right;
  }
```
