### ISSUE TITLE
Styling on chat control

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#2062]
### What went wrong? 🤔

A piece of code worked in 4.0.0.dev2 to style the chat control in a certain way:
![image](https://github.com/user-attachments/assets/25921b2c-5587-487b-8972-27fe8e466f10)

It now does not work in 4.0.0, the avatar and username of the sender are not there anymore:
![image](https://github.com/user-attachments/assets/5bc3764f-170b-49a3-924f-658cbab006a0)

How can I fix my code to resolve this in 4.0.0?

In `main.py`:
```python
import taipy.gui.builder as tgb
from taipy.gui import Gui

# The user interacts with the Python interpreter
users = ["Human", "Result"]
messages: list[tuple[str, str, str]] = []

# ------------------------------
# Action function
# ------------------------------


def evaluate(state, var_name: str, payload: dict):
    # Retrieve the callback parameters
    (_, _, expression, sender_id) = payload.get("args", [])
    print(sender_id)
    print(expression)

    # Add the input content as a sent message
    messages.append((f"{len(messages)}", expression, sender_id))
    print(messages)

    # Default message used if evaluation fails
    result = "Invalid expression"
    try:
        # Evaluate the expression and store the result
        result = f"{eval(expression)}"
    except Exception:
        pass

    # Add the result as an incoming message
    messages.append((f"{len(messages)}", result, users[1]))
    print(messages)

    state.messages = messages


# ------------------------------
# Create page object
# ------------------------------

with tgb.Page() as page:
    tgb.chat(
        "{messages}",
        users=users,
        on_action=evaluate,
        sender_id="{users[0]}",
        # * In this case, always Human
    )

# ------------------------------
# Main app
# ------------------------------

if __name__ == "__main__":
    print("Starting calculator...")
    Gui(page).run(dark_mode=True)
```

In `main.css`:
```css
/* receiver order */
.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root {
    flex-direction: row-reverse;
}
/* receiver avatar */
.taipy-chat-sent > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
}
/* receiver name */
.taipy-chat-sent .MuiStack-root .MuiStack-root .MuiBox-root {
 text-align: end;
 margin-right: -36px;
 padding-right: 0;
}

/* received avatar */
.taipy-chat-received > .MuiGrid2-root > .MuiStack-root > .MuiBox-root {
    padding-top: 1em;
}

/* received user name */
.taipy-chat-received .MuiStack-root .MuiStack-root .MuiBox-root {
    margin-left: -44px;
    padding-left: 0;
}
```

### Version of Taipy

4.0.0

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)
