### ISSUE TITLE
[Refactor] Improve navbar stylekit

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#2637]
### 📌 Description

The original navbar is not very attractive. The goal is to improve it without using CSS and make it a default.

This comes with a plan to improve the overall stylekit.

![Image](https://github.com/user-attachments/assets/6c5ff9b4-ba36-4b09-a941-5f84b8ad737b)

->

![Image](https://github.com/user-attachments/assets/31fcb476-bcf5-49f0-850e-3dce25e1e959)

```css
/* Change the color of the tabs */
.header .MuiButtonBase-root.MuiTab-root{
    border: 1px solid var(--color-primary); /* Thin line with 1px width, change color as needed */
    border-radius: 25px; /* Adjust this value for more or less rounding */
    padding: 10px; /* Optional: adds padding inside the rounded border */
    margin: 10px;
    text-transform: none;
    width: 12%;
}

.header .MuiButtonBase-root.MuiTab-root.Mui-selected{
    background-color: var(--color-primary);
    color: white;
}
```

### 📜 Code of Conduct

- [x] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+) to avoid duplicates.
- [ ] I am willing to work on this issue (optional)

### ✅ Acceptance Criteria

- [ ] The refactored code maintains existing functionality without breaking changes.
- [ ] Any new code is covered by unit tests.
- [ ] Code coverage remains at least 90%.
- [ ] Performance improvements are documented, if applicable.
