### ISSUE TITLE
Make more MUI classes available for Buttons

### ISSUE THREAD

**Issue by AAstridVH** [Avaiga/taipy#588]
Make the MUI classes "Small", "Medium" and "Large" available for buttons.

https://mui.com/material-ui/react-button/

![image](https://github.com/Avaiga/taipy/assets/96520448/01457b92-6452-4219-b28d-f83f86b2a8ae)

**Comment by FlorianJacta** [comment]
This issue comes from a user on Discord. It is quite hard to change the size of a button if you don't know CSS. 

main.py:

```python
from taipy import Gui 

buttons = """
<|Small|button|class_name=smallButton|>
<|Big|button|class_name=bigButton|>"
"""

Gui(buttons).run()
```

main.css:
```css
.smallButton{
    min-height: unset;
    line-height: 1.2rem;
    padding: 0;
    font-size: 1rem;
    text-transform: initial;
}

.bigButton{
    min-height: unset;
    line-height: 3.6rem;
    padding: 0;
    font-size: 3rem;
    text-transform: initial;
}
```

![image](https://github.com/Avaiga/taipy/assets/98709993/5021b97a-8307-478d-9380-c3f622e2854b)

## Environment

Taipy 3.0.0
