### ISSUE TITLE
Facilitate the change of size in button

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#589]
## Issue

It is quite hard to change the size of a button if you don't know CSS. 

main.py:

```python
from taipy import Gui 

buttons = """
<|Small|button|class_name=smallButton|>
<|Big|button|class_name=bigButton|>"
"""

Gui(buttons).run()
```

main.css:
```css
.smallButton{
    min-height: unset;
    line-height: 1.2rem;
    padding: 0;
    font-size: 1rem;
    text-transform: initial;
}

.bigButton{
    min-height: unset;
    line-height: 3.6rem;
    padding: 0;
    font-size: 3rem;
    text-transform: initial;
}
```

![image](https://github.com/Avaiga/taipy/assets/98709993/5021b97a-8307-478d-9380-c3f622e2854b)

## Possible improvement

We could use/open Material UI properties. The [*size* property](https://mui.com/material-ui/api/button/#Button-prop-size) is available through Material UI. We could use the stylekit to fit this gap or say that CSS is enough.

## Environment

Taipy 3.0.0
